### ISSUE TITLE
Newb Issue Unhandled rejection Error: 401

### ISSUE THREAD

**Issue by johnsonld123** [dgmltn/pimatic-wink#1]
I keep getting this error for my wink plugin,
Unhandled rejection Error: 401
    at maybeWrapAsError (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:70:12)
    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise_resolver.js:41:50
    at /home/pi/pimatic-app/node_modules/pimatic-wink/wink-node.js:335:21
    at IncomingMessage.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-wink/wink-node.js:119:21)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

Here is my config:

  { 
      "plugin": "wink",
      "client_id": "8888888888888888888888888",
      "client_secret": 8888888888888888888",
      "username": "johnsonl99999999999",
      "password": "Gr3300000000000"
    },

Using android or my client info ends the same.

**Comment by enishoca** [comment]
Please try the latest version, almost all the communications with Wink have been changed.  
Closing this issue since this would not be relevant any more.
